name: Deploy Context7 MCP

on:
  push:
    branches: [ master, main ]
    paths:
      - 'context7-mcp-update/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Context7 MCP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        run: |
          cd context7-mcp-update
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}